version: '0'

services:
  app1:
    container_name: app1
    build: ./api
    ports:
      - "3001:3000"
    environment:
      - MESSAGE=Bienvenido a Lab02 - Diego

  app2:
    container_name: app2
    build: ./api
    ports:
      - "3002:3000"
    environment:
      - MESSAGE=Bienvenido a Lab02 - Mauricio

  app3:
    container_name: app3
    build: ./api
    ports:
      - "3003:3000"
    environment:
      - MESSAGE=Bienvenido al Lab02 - Rodriguez
  
  db:
    image: postgres:14
    container_name: db_postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=PASSWORD
    - POSTGRES_USER=DIEGO
    - POSTGRES_DB=SEM2
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data

volumes:
  db_data:
